### ISSUE TITLE
Consider using image CDN

### ISSUE THREAD

**Issue by pnijhara** [SSGSA-dev/ssgsa-application-portal#140]
Consider using CDN for faster loading of images. Even though we are using the Image tag provided by Nextjs for the SSR of the images. Still, those images are not loading as fast as they should be. 
@roshnet @himanshuvarandani

**Comment by himanshuvarandani** [comment]
This issue is created due to Nextjs Image tag because it uses lazy loading as default behaviour as mentioned [here](https://stackoverflow.com/questions/66637391/next-images-components-are-too-slow-to-appear#:~:text=The%20problem%20is%20that%20the,recommended%20way%20is%20using%20priority%20.)

It means we can provide priority attribute to be true to the required image tag

**Comment by pnijhara** [comment]
@himanshuvarandani please try this.

**Comment by himanshuvarandani** [comment]
I have already tried it in development mode, just want to know on which images we have to set priority.

**Comment by pnijhara** [comment]
Try on the index page, especially on the slider images. If that works, we can set priority accordingly.
